CREATE TABLESPACE T_DICT DATAFILE 'C:\app\BaseVood\vood\vood\T_DICT.DAT' SIZE 1M REUSE AUTOEXTEND ON NEXT 1M;
CREATE TABLESPACE I_DICT DATAFILE 'C:\app\BaseVood\vood\vood\I_DICT.DAT' SIZE 1M REUSE AUTOEXTEND ON NEXT 1M;
/
