Create USER "VOOD" IDENTIFIED BY "vood"
DEFAULT TABLESPACE "T_DICT"
TEMPORARY TABLESPACE "TEMP";
/
commit;

ALTER USER "VOOD"
ACCOUNT UNLOCK;
/
commit;
-- QUOTAS

-- ROLES
--ALTER USER "VOOD" DEFAULT ROLE "CONNECT";
GRANT "AQ_ADMINISTRATOR_ROLE" TO "VOOD" ;
GRANT "DBA" TO "VOOD" ;
/
commit;
